language: scala
sudo: false
scala:
  - 2.10.5
  - 2.11.6
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalastyle && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls
